name: DAST - OWASP ZAP Scan

on:
  workflow_call:

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Start Services
        run: |
          pnpm install --frozen-lockfile

          echo "Starting Admin Service..."
          pnpm --filter admin-service run dev &

          echo "Starting User Service..."
          pnpm --filter user-service run dev &

          echo "Starting Frontend..."
          pnpm --filter frontend run dev &

          echo "Waiting for services..."
          sleep 30


      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:3000"
          cmd_options: '-a'
          allow_issue_writing: false
        continue-on-error: true

      - name: Upload ZAP baseline reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-baseline-reports
          path: 'zap_report.html'