name: Deploy to Staging

on:
  release:
    types: [published]

jobs:
  deploy:
    
    name: Deploy to staging 
    runs-on: ubuntu-latest
    environment: 
      name: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          # Use the Docker container names as the hostnames
          echo "NEXT_PUBLIC_AUTH_API_URL=http://admin_api:5001" >> .env
          echo "NEXT_PUBLIC_USER_API_URL=http://user_api:5002" >> .env
          
          # These are also needed for your Next.js rewrites
          echo "ADMIN_SERVICE_URL=http://admin_api:5001" >> .env
          echo "FILE_SERVICE_URL=http://user_api:5002" >> .env
          
          # Add the rest of your secrets
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env

      - name: Build and Run with Docker Compose
        run: |
          docker compose build
          docker compose up -d

      - name: Send Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[DevOps] Staging Updated"
          to: ER_Poi_Voon@np.edu.sg, lucastoh06@gmail.com
          from: DevOps Team
          body: |
            A new release has been published and deployed to Staging.
            
            Release Version: ${{ github.event.release.tag_name }}
            Released By: ${{ github.actor }}
            Deployment Target: Github
            
            