name: Frontend CI

on:
  workflow_call:
      

jobs:
  frontend_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Dependency Audit (SCA)
        run: pnpm audit --prod --audit-level=high

      - name: Format & Lint
        run: |
          pnpm run format:check
          pnpm run lint

      - name: Next.js Build Check
        run: pnpm run build

      - name: Build frontend (standalone)
        run: |
          NODE_ENV=production pnpm run build

      - name: Create .env file
        run: |
          touch .env
          # Use the Docker container names as the hostnames
          echo "NEXT_PUBLIC_AUTH_API_URL=http://admin_api:5001" >> .env
          echo "NEXT_PUBLIC_USER_API_URL=http://user_api:5002" >> .env
          
          # These are also needed for your Next.js rewrites
          echo "ADMIN_SERVICE_URL=http://admin_api:5001" >> .env
          echo "FILE_SERVICE_URL=http://user_api:5002" >> .env
          
          # Add the rest of your secrets
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .en

      - name: Start frontend & dependencies
        run: docker compose up -d frontend

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress
        run: pnpm exec cypress run

