name: Frontend CI

on:
  workflow_call:
      

jobs:
  frontend_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Dependency Audit (SCA)
        run: pnpm audit --prod --audit-level=high

      - name: Format & Lint
        run: |
          pnpm run format:check
          pnpm run lint

      - name: Next.js Build Check
        run: pnpm run build

      - name: Build frontend (standalone)
        run: |
          NODE_ENV=production pnpm run build

      - name: Start frontend & dependencies
        run: docker compose up -d frontend admin-service user-service

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress
        run: pnpm exec cypress run
        env:
          ADMIN_SERVICE_URL: http://admin_api:5001
          FILE_SERVICE_URL: http://user_api:5002
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
