name: CI/CD Master Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
    
permissions:
  contents: read
  security-events: write
  actions: read
  
jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml
  sast:
    uses: ./.github/workflows/SAST.yaml
  dast:
    uses: ./.github/workflows/DAST.yaml
  sca:
    uses: ./.github/workflows/SCA.yaml

  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    needs: [frontend, unit-tests, sast, dast, sca]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Version Tag
        id: tag
        run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.VERSION }}
          name: Release ${{ steps.tag.outputs.VERSION }}
          draft: true  
          prerelease: false
          generate_release_notes: true

  send-email-notification:
    runs-on: ubuntu-latest
    needs: [frontend, unit-tests, sast, dast, sca]
    if: always() # This ensures the email sends even if one check fails
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[DevOps Report] CI/CD Pipeline Results"
          to: ER_Poi_Voon@np.edu.sg, lucastoh06@gmail.com, lucas.yeo69@gmail.com, chenjy0142@gmail.com, lim06@gmail.com, s10257575@connect.np.edu.sg, ongjunhao2609@gmail.com
          from: DevOps Team 1
          body: |
            CI/CD Pipeline Report for ${{ github.repository }}
            =================================================
            Status Results:
            - Frontend CI: ${{ needs.frontend.result }}
            - Unit Tests: ${{ needs.unit-tests.result }}
            - SAST (CodeQL): ${{ needs.sast.result }}
            - DAST (ZAP): ${{ needs.dast.result }}
            - SCA (Dependencies): ${{ needs.sca.result }}
            
            View full details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}