name: SCA - Dependency Vulnerability Scan

on:
  workflow_call:

jobs:
  sca_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Audit Admin Service
        run: |
          cd services/admin-service
          pnpm install --frozen-lockfile
          pnpm audit --prod --audit-level=high

      - name: Audit User Service
        run: |
          cd services/user-service
          pnpm install --frozen-lockfile
          pnpm audit --prod --audit-level=high

      - name: Audit Frontend
        run: |
          cd frontend
          pnpm install --frozen-lockfile
          pnpm audit --prod --audit-level=high